### PR TITLE
Revision updates

### PR DESCRIPTION
**Pull request by yzhouchen0426**
Updated README and added Trained models

### CODE REVIEW

**Comment by apurvakalia** [comment]
Just a couple of comments:
- Some results mentioned in the readme of github (like improvement by 23.7% etc) seems a bit out of place in a readme. Is that required?
- Looks like we are not changing the code in any way. Do we need to add in the changes I did for batching for running large candidate lists?
- You should mention somewhere the names of the pretrained model weight files in the readme

**Review by apurvakalia — COMMENTED** [review]
Changes look good to me

**Comment by sohahassoun** [comment]
thank you




*Soha HassounProfessorDepartment of Computer ScienceTufts University*

*http://www.cs.tufts.edu/~soha* <http://www.cs.tufts.edu/~soha>

**Review by apurvakalia — APPROVED** [review]
Approved for merging

**Pull request merged**
